# This script contains functions for a "fuzzy" lexical frequency merge (using a database of
# your choice) that will first try a perfect match and then fall back to a less ideal
# matching when the data is not available.
# Also contains functions for classic lexical diversity indexes and moving-average TTR.
#
library(data.table, quietly = TRUE)

#' Expand a Lexical Database with French Plural Forms
#'
#' Generates plural candidates for each token in the database and appends them
#' as new rows. Plurals that already exist in the db are skipped.
#' The generated rows inherit all columns from the singular entry (same frequency).
#'
#' @param dt_lexical A data.table containing the lexical database.
#' @param token_col Name of the token column.
#' @returns A data.table with the original rows plus generated plural rows.
expand_lexical_db_plurals <- function(dt_lexical, token_col = "token",
                                     upos_col = "upos", freq_col = "freq_u") {
  dt <- copy(dt_lexical)

  tokens <- dt[[token_col]]

  # Generate plural candidates using French rules
  # Each rule produces one candidate; we collect all unique forms.
  plurals_s    <- paste0(tokens, "s")                          # chat -> chats
  plurals_x    <- paste0(tokens, "x")                          # bijou -> bijoux
  plurals_eaux <- sub("eau$", "eaux", tokens)                  # chateau -> chateaux
  plurals_aux  <- sub("al$", "aux", tokens)                    # animal -> animaux

  # Build a long table of (original_token, plural_form)
  dt_candidates <- rbindlist(list(
    data.table(orig = tokens, plural = plurals_s),
    data.table(orig = tokens, plural = plurals_x),
    data.table(orig = tokens, plural = plurals_eaux),
    data.table(orig = tokens, plural = plurals_aux)
  ))

  # Keep only candidates that actually differ from the original
  dt_candidates <- dt_candidates[orig != plural]
  # Remove duplicates (same plural generated by different rules, keep first orig)
  dt_candidates <- unique(dt_candidates, by = "plural")
  # Remove plurals that already exist as tokens in the db
  dt_candidates <- dt_candidates[!plural %in% tokens]

  if (nrow(dt_candidates) == 0L) {
    dt[, is_generated_plural := FALSE]
    return(dt)
  }

  # Merge back to get all columns from the singular entry.
  # allow.cartesian = TRUE because one singular may have multiple rows (e.g.
  # different UPOS), and we want to carry all of them over to the plural form.
  dt_new <- merge(dt_candidates, dt, by.x = "orig", by.y = token_col,
                  all.x = TRUE, sort = FALSE, allow.cartesian = TRUE)
  dt_new[, orig := NULL]
  setnames(dt_new, "plural", token_col)

  # Deduplicate: if the same plural (+ upos if present) was generated from
  # different rules or singulars, keep only the row with the highest frequency.
  dedup_cols <- if (upos_col %in% names(dt_new)) c(token_col, upos_col) else token_col
  setorderv(dt_new, freq_col, order = -1L)
  dt_new <- unique(dt_new, by = dedup_cols)

  # Flag generated rows
  dt[, is_generated_plural := FALSE]
  dt_new[, is_generated_plural := TRUE]

  # Reorder columns to match
  setcolorder(dt_new, names(dt))

  rbindlist(list(dt, dt_new), use.names = TRUE)
}


#' Fuzzy Match Between Corpus and Lexical Database
#'
#' @param dt_corpus A data.table containing the corpus to be annotated.
#' @param dt_lexical A data.table containing the lexical database.
#' @param freq_col A string specifying the name of the frequency column.
#' @param prefix A string specifying the prefix to add to lexical database columns.
#' @param token_col Name of the token column in the corpus and database.
#' @param lemma_col Name of the lemma column in the corpus.
#' @param upos_col Name of the part-of-speech column in the corpus and database.
#' @param id_col Name of the unique identifier column for tokens in the corpus.
#' @param verbose Logical; if TRUE, print progress information. Defaults to FALSE.
#'
#' @returns A data.table containing the merged corpus and lexical database.
fuzzy_match_lexical_db <- function(dt_corpus, dt_lexical,
                                   freq_col = "freq_u",
                                   prefix = "lexicaldb",
                                   token_col = "token",
                                   lemma_col = "lemma",
                                   upos_col = "upos",
                                   id_col = "vrai_token_id",
                                   strip_accents = FALSE,
                                   verbose = FALSE) {

  
  # Deduplicate matches by id, keeping the row with the highest sorting column value.
  deduplicate_matches <- function(data, id_col, sorting_col) {
    data <- data[order(get(id_col), -get(sorting_col))]
    data <- data[!duplicated(get(id_col))]
    return(data)
  }
  
  # Copy data for safety
  dt_corpus <- setDT(copy(dt_corpus))
  dt_lexical <- setDT(copy(dt_lexical))
  
  # Validation checks
  if (!(token_col %in% colnames(dt_lexical))) stop("The token column does not exist in the lexical db.")
  if (!(freq_col %in% colnames(dt_lexical))) stop("The frequency column does not exist in the lexical db.")
  if (!all(c(token_col, lemma_col, upos_col, id_col) %in% colnames(dt_corpus))) {
    stop("The corpus db does not have all required columns.")
  }
  
  # Lowercase tokens and lemmas for case-insensitive matching
  dt_corpus[, (token_col) := tolower(get(token_col))]
  dt_corpus[, (lemma_col) := tolower(get(lemma_col))]
  dt_lexical[, (token_col) := tolower(get(token_col))]
  if (lemma_col %in% colnames(dt_lexical)) {
    dt_lexical[, (lemma_col) := tolower(get(lemma_col))]
  }

  # Does the lexical db have a lemma column?
  db_has_lemma <- lemma_col %in% colnames(dt_lexical)

  # Optional accent stripping
  if (strip_accents) {
    if (!requireNamespace("stringi", quietly = TRUE)) {
      stop("Package 'stringi' is required for strip_accents = TRUE.")
    }
    # Strip accents from a character vector using stringi transliteration.
    strip <- function(x) stringi::stri_trans_general(x, "Latin-ASCII")
    dt_corpus[, (token_col) := strip(get(token_col))]
    dt_corpus[, (lemma_col) := strip(get(lemma_col))]
    dt_lexical[, (token_col) := strip(get(token_col))]
    if (db_has_lemma) dt_lexical[, (lemma_col) := strip(get(lemma_col))]
  }

  # Sorting column for prioritization
  dt_lexical[, .sorting_col := get(freq_col)]

  # Helper: subset of lexical db without upos/lemma (for token-key-only merges)
  lex_no_upos_lemma <- dt_lexical[, .SD, .SDcols = setdiff(names(dt_lexical), c(upos_col, lemma_col))]
  # Helper: subset without upos/token (for lemma-key merges, when db has lemma)
  if (db_has_lemma) {
    lex_by_lemma <- dt_lexical[, .SD, .SDcols = setdiff(names(dt_lexical), c(upos_col, token_col))]
  }

  # Track matched IDs across steps
  matched_ids <- character(0)
  results <- list()

  # Return corpus rows not yet matched to the lexical database.
  remaining <- function() dt_corpus[!get(id_col) %in% matched_ids]

  # Step 1: Exact match (token + upos)
  if (upos_col %in% colnames(dt_lexical)) {
    dt_step <- merge(dt_corpus, dt_lexical,
                     by.x = c(token_col, upos_col),
                     by.y = c(token_col, upos_col),
                     all.x = FALSE, sort = FALSE)
    dt_step <- deduplicate_matches(dt_step, id_col, ".sorting_col")
    dt_step[, match_level := "exact"]
    matched_ids <- c(matched_ids, dt_step[[id_col]])
    results <- c(results, list(dt_step))
    if (verbose) cat("Exact matches (token+upos):  ", nrow(dt_step), "\n")
  }

  # Step 2: Token-only match
  dt_step <- merge(remaining(), lex_no_upos_lemma,
                   by.x = token_col, by.y = token_col,
                   all.x = FALSE, sort = FALSE)
  dt_step <- deduplicate_matches(dt_step, id_col, ".sorting_col")
  dt_step[, match_level := "token_only"]
  matched_ids <- c(matched_ids, dt_step[[id_col]])
  results <- c(results, list(dt_step))
  if (verbose) cat("Token-only matches:          ", nrow(dt_step), "\n")

  # Step 3: Lemma-to-token match (corpus lemma vs db token)
  dt_step <- merge(remaining(), lex_no_upos_lemma,
                   by.x = lemma_col, by.y = token_col,
                   all.x = FALSE, sort = FALSE)
  dt_step <- deduplicate_matches(dt_step, id_col, ".sorting_col")
  dt_step[, match_level := "lemma_to_token"]
  matched_ids <- c(matched_ids, dt_step[[id_col]])
  results <- c(results, list(dt_step))
  if (verbose) cat("Lemma-to-token matches:      ", nrow(dt_step), "\n")

  # Step 4: Token-to-lemma match (corpus token vs db lemma, if db has lemma)
  if (db_has_lemma) {
    dt_step <- merge(remaining(), lex_by_lemma,
                     by.x = token_col, by.y = lemma_col,
                     all.x = FALSE, sort = FALSE)
    dt_step <- deduplicate_matches(dt_step, id_col, ".sorting_col")
    dt_step[, match_level := "token_to_lemma"]
    matched_ids <- c(matched_ids, dt_step[[id_col]])
    results <- c(results, list(dt_step))
    if (verbose) cat("Token-to-lemma matches:      ", nrow(dt_step), "\n")
  }

  # Step 5: Lemma-to-lemma match (corpus lemma vs db lemma, if db has lemma)
  if (db_has_lemma) {
    dt_step <- merge(remaining(), lex_by_lemma,
                     by.x = lemma_col, by.y = lemma_col,
                     all.x = FALSE, sort = FALSE)
    dt_step <- deduplicate_matches(dt_step, id_col, ".sorting_col")
    dt_step[, match_level := "lemma_to_lemma"]
    matched_ids <- c(matched_ids, dt_step[[id_col]])
    results <- c(results, list(dt_step))
    if (verbose) cat("Lemma-to-lemma matches:      ", nrow(dt_step), "\n")
  }

  # Orphans (unmatched tokens)
  dt_orphans <- remaining()
  dt_orphans[, match_level := "none"]
  results <- c(results, list(dt_orphans))
  if (verbose) cat("Unmatched tokens:            ", nrow(dt_orphans), "\n")

  # Combine results
  dt_merged <- rbindlist(results, fill = TRUE)
  dt_merged <- dt_merged[order(get(id_col))]

  # Remove sorting column
  dt_merged[, .sorting_col := NULL]

  # Rename new columns
  cols_to_rename <- setdiff(names(dt_lexical), c(token_col, upos_col, ".sorting_col"))
  setnames(dt_merged, cols_to_rename, paste0(prefix, "_", cols_to_rename))
  setnames(dt_merged, "match_level", paste0(prefix, "_match_level"))

  return(dt_merged)
}



# OOV frequency imputation ----
#
# Multiple methods for handling out-of-vocabulary tokens when matching against
# lexical frequency databases. Each impute_*() function takes a data.table with
# NA values in a frequency column and fills them.
#
# Methods:
#   skip       - leave OOV as NA (baseline)
#   epsilon    - assign a small constant
#   per_doc_gt - legacy: redistribute N1 per document (document-dependent, flawed)
#   fixed_gt   - single N1/N value for all OOV (default, recommended)
#   sgt        - Simple Good-Turing: smoothed frequency spectrum (Gale & Sampson 1995)
#   chao1      - Chao1 estimator: estimate unseen types from N1²/(2*N2)
#   chao2      - Chao2 estimator: incidence-based, uses document presence/absence
#   upos_gt    - per-UPOS N1/N from lexicon


#' Compute Frequency Statistics from a Lexical Database
#'
#' Derives corpus-level frequency statistics needed by the OOV imputation
#' functions: total token count, hapax/dis legomena counts, minimum observed
#' frequency, the full frequency-of-frequencies spectrum, and optional
#' per-UPOS breakdowns.
#'
#' @param dt_lexical A data.table containing the lexical database.
#' @param freq Name of the raw frequency column.
#' @param freq_u Name of the per-million frequency column.
#' @param upos_col Name of the UPOS column (used for per-UPOS stats).
#' @returns A named list with elements \code{N}, \code{N1}, \code{N2},
#'   \code{V}, \code{min_freq}, \code{freq_spectrum} (a data.table), and
#'   \code{upos_stats} (a data.table or NULL).
lexical_db_stats <- function(dt_lexical, freq = "freq", freq_u = "freq_u",
                             upos_col = "upos") {

  freq_col_exists <- freq %in% names(dt_lexical)
  freq_u_col_exists <- freq_u %in% names(dt_lexical)

  if (!freq_col_exists && !freq_u_col_exists) {
    stop("Neither the 'freq' nor the 'freq_u' column was found in dt_lexical.")
  }

  if (freq_col_exists) {
    v_freq <- dt_lexical[[freq]]
  } else {
    v_freq <- dt_lexical[[freq_u]] * 1e6
  }

  N_token <- sum(v_freq, na.rm = TRUE)
  min_freq <- min(v_freq, na.rm = TRUE)

  # Frequency-of-frequencies spectrum: how many types have each frequency
  freq_table <- table(round(v_freq))
  freq_spectrum <- data.table(
    r = as.numeric(names(freq_table)),
    Nr = as.integer(freq_table)
  )
  setorder(freq_spectrum, r)

  N1_token <- if (nrow(freq_spectrum) > 0L) freq_spectrum$Nr[1L] else 0L
  N2_token <- if (nrow(freq_spectrum) > 1L) freq_spectrum$Nr[2L] else 0L
  V_types  <- nrow(dt_lexical)

  # Per-UPOS stats (if upos column exists)
  upos_stats <- NULL
  if (upos_col %in% names(dt_lexical)) {
    dt_tmp <- data.table(upos = dt_lexical[[upos_col]], freq = v_freq)
    dt_tmp <- dt_tmp[!is.na(upos)]
    upos_stats <- dt_tmp[, {
      fs <- table(round(freq))
      fs_sorted <- sort(as.numeric(names(fs)))
      .(N = sum(freq, na.rm = TRUE),
        N1 = if (length(fs) > 0L) as.integer(fs[as.character(fs_sorted[1L])]) else 0L,
        N2 = if (length(fs) > 1L) as.integer(fs[as.character(fs_sorted[2L])]) else 0L,
        V = .N)
    }, by = upos]
  }

  list(
    N = N_token,
    N1 = N1_token,
    N2 = N2_token,
    V = V_types,
    min_freq = min_freq,
    freq_spectrum = freq_spectrum,
    upos_stats = upos_stats
  )
}


# --- Individual imputation functions ---
# All take: dt (data.table), count_col (freq column name with NAs),
#           output_name (name for result column).
# Some also take mode ("raw"/"u"), db_stats, N_token, etc.


#' Impute OOV Frequencies: Skip (Leave as NA)
#'
#' Baseline method that leaves out-of-vocabulary tokens as \code{NA}.
#'
#' @param dt A data.table with a frequency column containing NAs for OOV tokens.
#' @param count_col Name of the frequency column.
#' @param output_name Optional name for the output column (if NULL, overwrites \code{count_col}).
#' @returns A copy of \code{dt} with OOV values left as NA.
impute_skip <- function(dt, count_col, output_name = NULL) {
  dt <- copy(dt)
  if (!is.null(output_name)) {
    dt[, (output_name) := .SD[[1]], .SDcols = count_col]
  }
  dt
}

#' Impute OOV Frequencies: Epsilon (Small Constant)
#'
#' Assigns a small constant to all out-of-vocabulary tokens.
#' Default epsilon is half the minimum observed frequency.
#'
#' @param dt A data.table with a frequency column containing NAs for OOV tokens.
#' @param count_col Name of the frequency column.
#' @param epsilon Numeric constant to assign to OOV tokens; if NULL, uses
#'   \code{min(observed) / 2}.
#' @param output_name Optional name for the output column.
#' @returns A copy of \code{dt} with OOV values replaced by \code{epsilon}.
impute_epsilon <- function(dt, count_col, epsilon = NULL, output_name = NULL) {
  dt <- copy(dt)

  if (is.null(epsilon)) {
    observed <- dt[[count_col]]
    epsilon <- min(observed, na.rm = TRUE) / 2
  }

  col <- if (!is.null(output_name)) output_name else count_col
  dt[, (col) := .SD[[1]], .SDcols = count_col]
  dt[is.na(get(col)), (col) := epsilon]
  dt
}

#' Impute OOV Frequencies: Per-Document Good-Turing (Legacy)
#'
#' Legacy method that redistributes the missing mass (N1) across each
#' document's OOV tokens independently. This means the same OOV word can
#' receive different imputed frequencies in different documents.
#' Kept for comparison; prefer \code{impute_fixed_gt} for new work.
#'
#' @param dt A data.table with a frequency column containing NAs for OOV tokens.
#'   Must contain a \code{doc_id} column.
#' @param count_col Name of the frequency column.
#' @param mode Either \code{"raw"} (raw counts) or \code{"u"} (per-million).
#' @param N_token Total token count from the lexical database.
#' @param N1_token Number of hapax legomena in the lexical database.
#' @param output_name Optional name for the output column.
#' @returns A copy of \code{dt} with OOV values imputed per document.
impute_per_doc_gt <- function(dt, count_col, mode = "raw", N_token, N1_token,
                              output_name = NULL) {
  stopifnot("doc_id" %in% names(dt))
  dt <- copy(dt)

  dt[, freq_impute := if (mode == "u") .SD[[1]] * N_token / 1e6 else .SD[[1]],
     .SDcols = count_col]

  doc_info <- dt[is.na(freq_impute), .N, by = doc_id]
  setnames(doc_info, "N", "n_missing")
  doc_info[, imputed_value := fifelse(n_missing > 0, N1_token / n_missing, 0)]

  dt <- merge(dt, doc_info[, .(doc_id, imputed_value)], by = "doc_id",
              all.x = TRUE, sort = FALSE)
  dt[is.na(freq_impute), freq_impute := imputed_value]

  if (mode == "u") dt[, freq_impute := freq_impute * 1e6 / N_token]

  if (!is.null(output_name)) setnames(dt, "freq_impute", output_name)
  dt[, imputed_value := NULL]
  dt
}

#' Impute OOV Frequencies: Fixed Good-Turing (Recommended Default)
#'
#' Assigns a single Good-Turing estimate (N1/N) to all out-of-vocabulary
#' tokens. This is the simplest correct estimate of the probability of an
#' unseen event.
#'
#' @param dt A data.table with a frequency column containing NAs for OOV tokens.
#' @param count_col Name of the frequency column.
#' @param mode Either \code{"raw"} (raw counts) or \code{"u"} (per-million).
#' @param N_token Total token count from the lexical database.
#' @param N1_token Number of hapax legomena in the lexical database.
#' @param output_name Optional name for the output column.
#' @returns A copy of \code{dt} with OOV values set to \code{N1/N}.
impute_fixed_gt <- function(dt, count_col, mode = "raw", N_token, N1_token,
                            output_name = NULL) {
  dt <- copy(dt)

  # Imputed value in raw scale
  gt_value_raw <- N1_token / N_token
  gt_value <- if (mode == "u") gt_value_raw * 1e6 / N_token else gt_value_raw

  col <- if (!is.null(output_name)) output_name else count_col
  dt[, (col) := .SD[[1]], .SDcols = count_col]
  dt[is.na(get(col)), (col) := gt_value]
  dt
}

#' Impute OOV Frequencies: Simple Good-Turing
#'
#' Smooths the frequency-of-frequencies spectrum via log-linear regression
#' (Gale & Sampson, 1995) and derives the unseen-type probability from the
#' smoothed curve. Falls back to \code{impute_fixed_gt} when the spectrum
#' has fewer than 5 points.
#'
#' @param dt A data.table with a frequency column containing NAs for OOV tokens.
#' @param count_col Name of the frequency column.
#' @param mode Either \code{"raw"} (raw counts) or \code{"u"} (per-million).
#' @param db_stats A list returned by \code{lexical_db_stats}.
#' @param output_name Optional name for the output column.
#' @returns A copy of \code{dt} with OOV values imputed via SGT.
impute_sgt <- function(dt, count_col, mode = "raw", db_stats,
                       output_name = NULL) {
  dt <- copy(dt)

  N <- db_stats$N
  spectrum <- copy(db_stats$freq_spectrum)

  # Need enough points to fit the log-linear model
  if (nrow(spectrum) < 5L) {
    warning("impute_sgt: frequency spectrum too sparse (", nrow(spectrum),
            " points); falling back to fixed GT.")
    return(impute_fixed_gt(dt, count_col, mode, N, db_stats$N1, output_name))
  }

  # Smooth N_r via linear regression on log(r) vs log(N_r)
  spectrum[, log_r := log(r)]
  spectrum[, log_Nr := log(Nr)]
  fit <- lm(log_Nr ~ log_r, data = spectrum)
  spectrum[, Nr_smooth := exp(predict(fit))]

  # Adjusted count for unseen (r=0): total missing mass = N1/N
  p0 <- db_stats$N1 / N

  # Estimate number of unseen types from the smoothed spectrum
  # Extrapolate Nr_smooth at r approaching 0
  Nr0_smooth <- exp(predict(fit, newdata = data.frame(log_r = log(0.5))))
  V_unseen <- max(Nr0_smooth, 1)

  # Per-type unseen probability
  p_unseen_per_type <- p0 / V_unseen

  # Convert to the appropriate scale
  if (mode == "u") {
    imputed_value <- p_unseen_per_type * 1e6
  } else {
    imputed_value <- p_unseen_per_type * N
  }

  col <- if (!is.null(output_name)) output_name else count_col
  dt[, (col) := .SD[[1]], .SDcols = count_col]
  dt[is.na(get(col)), (col) := imputed_value]
  dt
}

#' Impute OOV Frequencies: Chao1 Abundance-Based Estimator
#'
#' Estimates the number of unseen types as \code{N1^2 / (2 * N2)} (Chao, 1984)
#' and distributes the total missing mass (N1/N) across those types.
#'
#' @param dt A data.table with a frequency column containing NAs for OOV tokens.
#' @param count_col Name of the frequency column.
#' @param mode Either \code{"raw"} (raw counts) or \code{"u"} (per-million).
#' @param db_stats A list returned by \code{lexical_db_stats}.
#' @param output_name Optional name for the output column.
#' @returns A copy of \code{dt} with OOV values imputed via Chao1.
impute_chao1 <- function(dt, count_col, mode = "raw", db_stats,
                         output_name = NULL) {
  dt <- copy(dt)

  N <- db_stats$N
  N1 <- db_stats$N1
  N2 <- db_stats$N2

  # Chao1 estimate of unseen types
  if (N2 > 0) {
    V_unseen <- (N1^2) / (2 * N2)
  } else {
    V_unseen <- N1 * (N1 - 1) / 2  # bias-corrected form when N2 == 0
  }
  V_unseen <- max(V_unseen, 1)

  # Total missing mass = N1/N, distributed across estimated unseen types
  p_per_type <- (N1 / N) / V_unseen

  if (mode == "u") {
    imputed_value <- p_per_type * 1e6
  } else {
    imputed_value <- p_per_type * N
  }

  col <- if (!is.null(output_name)) output_name else count_col
  dt[, (col) := .SD[[1]], .SDcols = count_col]
  dt[is.na(get(col)), (col) := imputed_value]
  dt
}

#' Impute OOV Frequencies: Chao2 Incidence-Based Estimator
#'
#' Incidence-based variant that estimates unseen types from document
#' presence/absence counts: q1 (types in exactly 1 document) and q2
#' (types in exactly 2 documents). Requires a \code{doc_id} column.
#'
#' @param dt A data.table with a frequency column containing NAs for OOV tokens.
#'   Must contain a \code{doc_id} column.
#' @param count_col Name of the frequency column.
#' @param mode Either \code{"raw"} (raw counts) or \code{"u"} (per-million).
#' @param db_stats A list returned by \code{lexical_db_stats}.
#' @param output_name Optional name for the output column.
#' @returns A copy of \code{dt} with OOV values imputed via Chao2.
impute_chao2 <- function(dt, count_col, mode = "raw", db_stats,
                         output_name = NULL) {
  stopifnot("doc_id" %in% names(dt))
  dt <- copy(dt)

  N <- db_stats$N

  # Compute incidence from the matched corpus data
  # q1: OOV types appearing in exactly 1 doc; q2: in exactly 2 docs
  oov_tokens <- dt[is.na(get(count_col)), .(token, doc_id)]

  if (nrow(oov_tokens) == 0L) {
    col <- if (!is.null(output_name)) output_name else count_col
    dt[, (col) := .SD[[1]], .SDcols = count_col]
    return(dt)
  }

  type_incidence <- oov_tokens[, .(n_docs = uniqueN(doc_id)), by = token]
  q1 <- sum(type_incidence$n_docs == 1L)
  q2 <- sum(type_incidence$n_docs == 2L)

  n_samples <- uniqueN(dt$doc_id)

  if (q2 > 0) {
    V_unseen <- ((n_samples - 1) / n_samples) * (q1^2) / (2 * q2)
  } else {
    V_unseen <- ((n_samples - 1) / n_samples) * q1 * (q1 - 1) / 2
  }
  V_unseen <- max(V_unseen, 1)

  # Total missing mass from the lexicon, distributed across unseen types
  p_per_type <- (db_stats$N1 / N) / V_unseen

  if (mode == "u") {
    imputed_value <- p_per_type * 1e6
  } else {
    imputed_value <- p_per_type * N
  }

  col <- if (!is.null(output_name)) output_name else count_col
  dt[, (col) := .SD[[1]], .SDcols = count_col]
  dt[is.na(get(col)), (col) := imputed_value]
  dt
}

#' Impute OOV Frequencies: Per-UPOS Stratified Good-Turing
#'
#' Computes a separate Good-Turing estimate (N1/N) for each UPOS category
#' in the lexicon. Tokens whose UPOS is missing or absent from the lexicon
#' fall back to the global fixed GT value.
#'
#' @param dt A data.table with a frequency column containing NAs for OOV tokens.
#' @param count_col Name of the frequency column.
#' @param mode Either \code{"raw"} (raw counts) or \code{"u"} (per-million).
#' @param db_stats A list returned by \code{lexical_db_stats}.
#' @param upos_col Name of the UPOS column.
#' @param output_name Optional name for the output column.
#' @returns A copy of \code{dt} with OOV values imputed per UPOS category.
impute_upos_gt <- function(dt, count_col, mode = "raw", db_stats,
                           upos_col = "upos", output_name = NULL) {
  dt <- copy(dt)

  N <- db_stats$N
  N1 <- db_stats$N1

  # Global fallback value
  global_gt <- if (mode == "u") (N1 / N) * 1e6 / N else N1 / N

  col <- if (!is.null(output_name)) output_name else count_col
  dt[, (col) := .SD[[1]], .SDcols = count_col]

  if (is.null(db_stats$upos_stats) || !upos_col %in% names(dt)) {
    # No UPOS info available: fall back to global fixed GT
    dt[is.na(get(col)), (col) := global_gt]
    return(dt)
  }

  # Build lookup of per-UPOS imputed values
  ustats <- copy(db_stats$upos_stats)
  ustats[, gt_value := fifelse(
    N > 0,
    if (mode == "u") (N1 / N) * 1e6 / db_stats$N else N1 / db_stats$N,
    global_gt
  )]

  # Merge per-UPOS values
  oov_idx <- which(is.na(dt[[col]]))
  if (length(oov_idx) > 0L) {
    oov_upos <- dt[[upos_col]][oov_idx]
    upos_lookup <- setNames(ustats$gt_value, ustats$upos)
    imputed <- upos_lookup[oov_upos]
    # Fall back to global for unknown UPOS categories
    imputed[is.na(imputed)] <- global_gt
    set(dt, i = oov_idx, j = col, value = imputed)
  }

  dt
}


#' Merge Lexical Frequencies and Apply OOV Imputation
#'
#' Main wrapper that performs a fuzzy merge between a parsed corpus and a
#' lexical frequency database, then applies one of several out-of-vocabulary
#' imputation strategies to fill missing frequencies.
#'
#' @param parsed_corpus A data.table with columns \code{doc_id}, \code{token},
#'   \code{lemma}, \code{upos}, and \code{vrai_token_id}.
#' @param lexical_db A data.table containing the lexical database.
#' @param prefix String prefix added to lexical database columns after merge.
#' @param freq_col Name of the frequency column in \code{lexical_db}.
#' @param mode Either \code{"raw"} (raw counts) or \code{"u"} (per-million).
#' @param method Imputation method: one of \code{"fixed_gt"} (default),
#'   \code{"skip"}, \code{"epsilon"}, \code{"per_doc_gt"}, \code{"sgt"},
#'   \code{"chao1"}, \code{"chao2"}, or \code{"upos_gt"}.
#' @param epsilon Constant for the epsilon method (passed to \code{impute_epsilon}).
#' @param N_token Optional manual override for total token count.
#' @param N1_token Optional manual override for hapax count.
#' @returns A data.table with merged frequencies and an imputed frequency column.
add_lexical_freq_with_imputation <- function(parsed_corpus,
                                             lexical_db,
                                             prefix = "",
                                             freq_col = "freq",
                                             mode = "raw",  # or "u"
                                             method = c("fixed_gt", "skip",
                                                        "epsilon", "per_doc_gt",
                                                        "sgt", "chao1", "chao2",
                                                        "upos_gt"),
                                             epsilon = NULL,
                                             N_token = NULL,
                                             N1_token = NULL) {
  method <- match.arg(method)

  stopifnot("doc_id" %in% names(parsed_corpus))
  stopifnot("token" %in% names(parsed_corpus))
  stopifnot(freq_col %in% names(lexical_db))
  stopifnot(mode %in% c("raw", "u"))

  # Step 1: Merge lexical database
  matched <- fuzzy_match_lexical_db(parsed_corpus, lexical_db, prefix = prefix)

  # Step 2: Compute lexicon stats
  db_stats <- lexical_db_stats(
    lexical_db,
    freq = if (mode == "raw") freq_col else "freq",
    freq_u = if (mode == "u") freq_col else "freq_u"
  )
  # Allow manual override of N and N1
  if (!is.null(N_token)) db_stats$N <- N_token
  if (!is.null(N1_token)) db_stats$N1 <- N1_token

  # Step 3: Dispatch to imputation method
  count_col <- paste0(prefix, "_", freq_col)
  out_col <- paste0(prefix, "_", freq_col, "_imputed")

  matched <- switch(method,
    skip = impute_skip(matched, count_col, output_name = out_col),
    epsilon = impute_epsilon(matched, count_col, epsilon = epsilon,
                             output_name = out_col),
    per_doc_gt = impute_per_doc_gt(matched, count_col, mode = mode,
                                   N_token = db_stats$N, N1_token = db_stats$N1,
                                   output_name = out_col),
    fixed_gt = impute_fixed_gt(matched, count_col, mode = mode,
                               N_token = db_stats$N, N1_token = db_stats$N1,
                               output_name = out_col),
    sgt = impute_sgt(matched, count_col, mode = mode, db_stats = db_stats,
                     output_name = out_col),
    chao1 = impute_chao1(matched, count_col, mode = mode, db_stats = db_stats,
                         output_name = out_col),
    chao2 = impute_chao2(matched, count_col, mode = mode, db_stats = db_stats,
                         output_name = out_col),
    upos_gt = impute_upos_gt(matched, count_col, mode = mode, db_stats = db_stats,
                             output_name = out_col)
  )

  matched
}



# Lexical diversity -----

#' Calculate Type-Token Ratio
#'
#' Computes the ratio of unique types to total tokens. Accepts separate
#' vectors for tokens and types, allowing e.g. lemmas as the type unit.
#'
#' @param tokens A character vector of tokens.
#' @param types A character vector used to count unique types (can differ from \code{tokens}).
#' @returns A numeric scalar: number of unique types divided by number of tokens.
calculate_TTR <- function(tokens, types) {
  n_token <- length(tokens)
  n_type <- length(unique(types))
  ttr <- n_type / n_token
  return(ttr)
}

#' Calculate Moving-Average Type-Token Ratio (MATTR)
#'
#' Computes TTR over a sliding window using \code{zoo::rollapply} and
#' returns the mean across all windows. If the text is shorter than
#' \code{window_size}, the window is shrunk to the text length.
#'
#' @param tokens A character vector of tokens.
#' @param window_size Integer window width (default 50).
#' @returns A numeric scalar: mean TTR across all sliding windows.
calculate_moving_TTR <- function(tokens, window_size = 50) {
  # if text length is > window_size, change window_size to text length
  if (length(tokens) < window_size) {
    window_size <- length(tokens)
  }
  
  # Compute moving TTR using rollapply
  ttr_values <- zoo::rollapply(
    tokens, 
    width = window_size, 
    FUN = function(x) length(unique(x)) / length(x), 
    fill = NA, 
    align = "right"
  )
  
  # Remove NA values (incomplete windows at the beginning)
  ttr_values <- na.omit(ttr_values)
  
  # Average out all TTR values across segments
  mean_ttr <- mean(ttr_values)
  
  return(mean_ttr)
}

#' Calculate Maas Index of Lexical Diversity
#'
#' Computes Maas's index: \code{(log(N) - log(V)) / log(N^2)}, where N is
#' the number of tokens and V is the number of unique types. Lower values
#' indicate greater lexical diversity.
#'
#' @param tokens A character vector of tokens.
#' @param types A character vector used to count unique types.
#' @returns A numeric scalar: the Maas index.
calculate_maas <- function(tokens, types) {
  n_token <- length(tokens)
  n_type <- length(unique(types))
  maas <- (log(n_token) - log(n_type)) / log(n_token^2)
  return(maas)
}

#' Compute Simpson's D Measure from Token Frequencies
#'
#' Derives Simpson's diversity index from a token frequency distribution:
#' \code{D = sum(f_i * (f_i - 1)) / (N * (N - 1))}, where f_i is the
#' frequency of each type and N is the total number of tokens.
#'
#' @param tokens A character vector of tokens.
#' @returns A numeric scalar: Simpson's D measure.
D_measure_from_tokens <- function(tokens) {
  N <- length(tokens)  # Total number of tokens
  freq_table <- table(tokens)  # Frequency of each type
  V <- length(freq_table)  # Number of unique types
  
  # Create a table for fv(i, N): number of types occurring exactly i times
  fv <- table(freq_table)
  
  # Compute the D-measure using the formula
  D <- sum(as.numeric(names(fv)) * fv * 
             (as.numeric(names(fv)) - 1) / (N * (N - 1)))
  
  return(D)
}

#' Compute All Lexical Diversity Indexes per Document
#'
#' Wrapper that computes TTR, MATTR, Maas index, and Simpson's D for each
#' document. When a \code{upos} column is present, additional content-word-only
#' and verb-only variants are computed.
#'
#' @param df A data.table or data.frame with at least \code{doc_id} and
#'   \code{token} columns. Optional columns: \code{upos}, \code{start},
#'   \code{compte}.
#' @param upos Unused (kept for backwards compatibility).
#' @param content_upos Character vector of UPOS tags considered content words
#'   (default: NOUN, VERB, ADJ, ADV).
#' @param window_size Window width for MATTR (default 50).
#' @returns A data.table with one row per document and columns for each
#'   diversity index.
lexical_diversity_general <- function(df,
                                      upos = NA,
                                      content_upos = c("NOUN", "VERB", "ADJ", "ADV"),
                                      window_size = 50) {

  # check that a tokens vector is provided
  if (missing(df)) {
    stop("No corpus provided.")
  }

  # check that I have the required columns
  if (!all(c("token", "doc_id") %in% colnames(df))) {
    stop("The corpus db does not have all the required columns (doc_id, token).")
  }
  
  # Filter
  # if we have a start column, we can apply this rule to remove UDPipe-generated tokens
  if ("start" %in% colnames(df)) {
    df <- df %>% filter(!is.na(start))
  }
  
  # and if we have our "compte" custom column we can use that
  if ("compte" %in% colnames(df)) {
    df <- df %>% filter(compte)
  } else {
    # otherwise, we can at least remove punctuation as it does not count for a word
    df <- df %>% filter(!upos %in% c("PUNCT"))
  }
  
  df_result <- df %>%
    group_by(doc_id) %>%
    summarise(
      TTR = calculate_TTR(token, token),
      maas = calculate_maas(token, token),
      MATTR = calculate_moving_TTR(token, window_size),
      simpsons_D = D_measure_from_tokens(token)
    )
  
  # if we have a upos column in df, we can also do content words only
  # check if df has a upos column
  if ("upos" %in% colnames(df)) {
    df_result_extra <- df %>%
      filter(!is.na(upos) & upos %in% content_upos) %>%
      group_by(doc_id) %>%
      summarise(
        TTR_content = calculate_TTR(token, token),
        maas_content = calculate_maas(token, token),
        MATTR_content = calculate_moving_TTR(token, window_size),
        simpsons_D_content = D_measure_from_tokens(token),
      )
    df_result <- left_join(df_result, df_result_extra, by = "doc_id")
    
    df_result_verb <- df %>%
      filter(!is.na(upos) & upos %in% "VERB") %>%
      group_by(doc_id) %>%
      summarise(
        maas_verb = calculate_maas(token, token),
        simpsons_D_verb = D_measure_from_tokens(token),
      )
    
    df_result <- left_join(df_result, df_result_verb, by = "doc_id")
  }

  
  return(df_result)
}
